apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: tonijordanrodriguez6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "adminpass"
          - name: MYSQL_DATABASE
            value: "wordpress"
          - name: MYSQL_USER
            value: "wpuser"
          - name: MYSQL_PASSWORD
            value: "wppass"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: tonijordanrodriguez6-dev
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
