apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-openshift
  namespace: tonijordanrodriguez6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-openshift
  template:
    metadata:
      labels:
        app: hello-openshift
    spec:
      containers:
      - name: hello-openshift
        image: openshift/hello-openshift
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hello-openshift
  namespace: tonijordanrodriguez6-dev
spec:
  selector:
    app: hello-openshift
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: hello-openshift
  namespace: tonijordanrodriguez6-dev
spec:
  to:
    kind: Service
    name: hello-openshift
  port:
    targetPort: 8080
  tls:
    termination: edge
