apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: tonijordanrodriguez6-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:latest
        env:
          - name: WORDPRESS_DB_HOST
            value: "mysql"
          - name: WORDPRESS_DB_USER
            value: "wpuser"
          - name: WORDPRESS_DB_PASSWORD
            value: "wppass"
          - name: WORDPRESS_DB_NAME
            value: "wordpress"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: tonijordanrodriguez6-dev
spec:
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: wordpress
  namespace: tonijordanrodriguez6-dev
spec:
  to:
    kind: Service
    name: wordpress
  port:
    targetPort: 80
  tls:
    termination: edge
