apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: tonijordanrodriguez6-dev
type: Opaque
stringData:
  POSTGRES_DB: realworld
  POSTGRES_USER: realworld
  POSTGRES_PASSWORD: realworld123
