apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: app-role
  namespace: realworld
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: realworld
subjects:
  - kind: ServiceAccount
    name: default
    namespace: realworld
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
