apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: code-quality
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
  steps:
    - name: lint
      image: python:3.10
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        pip install flake8
        flake8 src