apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: checkout-repo
spec:
  params:
    - name: repo-url
      type: string
    - name: revision
      type: string
      default: "main"
  workspaces:
    - name: source
  steps:
    - name: clone
      image: alpine/git
      script: |
        #!/bin/sh
        git clone $(params.repo-url) --branch $(params.revision) $(workspaces.source.path)