apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-image
  namespace: tekton-pipelines
spec:
  params:
    - name: image-name
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=$(workspaces.source.path)/Dockerfile"
        - "--context=$(workspaces.source.path)"
        - "--destination=$(params.image-name)"
