apiVersion: v1
kind: Service
metadata:
  name: ci-listener-svc
  namespace: tekton-pipelines
spec:
  selector:
    app: tekton-triggers-webhook
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
