apiVersion: v1
kind: Service
metadata:
  name: ci-listener-svc
  namespace: tekton-pipelines
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    tekton.dev/eventListener: ci-listener
