apiVersion: triggers.tekton.dev/v1alpha1
kind: ClusterInterceptor
metadata:
  name: github
  annotations:
    tekton.dev/inject-ca: "true"
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      port: 443
      path: /github
