apiVersion: triggers.tekton.dev/v1beta1
kind: ClusterInterceptor
metadata:
  name: github
  namespace: tekton-pipelines
  annotations:
    tekton.dev/inject-ca: "true"
spec:
  clientConfig:
    service:
      name: tekton-triggers-webhook
      namespace: tekton-pipelines
      port: 8080  # Cambiado a 8080
      path: /github
