apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: ci-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-push
      bindings:
        - kind: TriggerBinding
          ref: github-binding
      template:
        ref: ci-template
